name: Lint and Test
on:
  push:
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js Latest
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: npm
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
  test:
    strategy:
      matrix:
        node: [14.x, 16.x, 18.x, 20.x, latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: npm
    - run: npm install
    - run: npm test
